version: "3.9"

services:
  backend:
    build: ./help-desk-server
    container_name: helpdesk-backend
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/helpdesk

  frontend:
    build: ./help-desk-web
    container_name: helpdesk-frontend
    ports:
      - "3000:80" # 80 no container nginx, 3000 na sua máquina
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: helpdesk-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helpdesk
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
